# Generated by Django 5.0.3 on 2024-04-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cadegory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='create_data',
            new_name='created_data',
        ),
    ]
